import { UserSelections } from '../types/index.js';

export type PresetName = 'minimal' | 'saas' | 'dashboard' | 'landing' | 'portfolio' | 'ecommerce' | 'blog-docs' | 'components-ui';


export const PRESETS: Record<PresetName, Partial<UserSelections>> = {
  minimal: {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'css-modules',
    ui: 'none',
    forms: 'none',
    state: 'none',
    routing: 'none',
    dataFetching: 'none',
    icons: 'none',
    structure: 'simple',

    optionalFeatures: [],
  },
  saas: {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'tailwind',
    ui: 'shadcn',
    forms: 'rhf-zod',
    state: 'zustand',
    routing: 'react-router',
    dataFetching: 'tanstack-query',
    icons: 'lucide',
    structure: 'feature-based',

  },
  dashboard: {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'tailwind',
    ui: 'shadcn',
    forms: 'rhf-zod',
    state: 'zustand',
    routing: 'react-router',
    dataFetching: 'tanstack-query',
    icons: 'lucide',
    structure: 'feature-based',

    aiInstructions: ['universal'],
  },
  landing: {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'tailwind',
    ui: 'shadcn',
    forms: 'none',
    state: 'none',
    routing: 'none',
    dataFetching: 'none',
    icons: 'lucide',
    structure: 'simple',

    optionalFeatures: ['animation', 'aiInstructions'],
    animation: 'framer-motion',
    aiInstructions: ['universal'],
  },
  portfolio: {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'tailwind',
    ui: 'none',
    forms: 'rhf-zod',
    state: 'none',
    routing: 'none',
    dataFetching: 'none',
    icons: 'lucide',
    structure: 'feature-based',
    optionalFeatures: ['animation'],
    animation: 'framer-motion',
  },
  ecommerce: {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'tailwind',
    ui: 'shadcn',
    forms: 'rhf-zod',
    state: 'zustand',
    routing: 'react-router',
    dataFetching: 'tanstack-query',
    icons: 'lucide',
    structure: 'feature-based',
  },
  'blog-docs': {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'tailwind',
    ui: 'none',
    forms: 'none',
    state: 'none',
    routing: 'react-router',
    dataFetching: 'none',
    icons: 'lucide',
    structure: 'feature-based',
  },
  'components-ui': {
    framework: 'react',
    variant: 'ts',
    language: 'typescript',
    styling: 'tailwind',
    ui: 'shadcn', // Using shadcn as base for component library
    forms: 'rhf-zod',
    state: 'none',
    routing: 'react-router',
    dataFetching: 'none',
    icons: 'lucide',
    structure: 'feature-based',
  },

};
